"""empty message

Revision ID: 525c694f2b1f
Revises: d366eff258a1
Create Date: 2026-01-29 20:32:27.771742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525c694f2b1f'
down_revision = 'd366eff258a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower_user')
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    op.create_table('follower_user',
    sa.Column('user_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_from'], ['user.id'], name='follower_user_user_from_fkey'),
    sa.ForeignKeyConstraint(['user_to'], ['follower.id'], name='follower_user_user_to_fkey')
    )
    # ### end Alembic commands ###
