"""empty message

Revision ID: d366eff258a1
Revises: 6b27c1f7c789
Create Date: 2026-01-29 19:34:43.317236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd366eff258a1'
down_revision = '6b27c1f7c789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower_user',
    sa.Column('user_from', sa.Integer(), nullable=True),
    sa.Column('user_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['follower.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower_user')
    op.drop_table('follower')
    # ### end Alembic commands ###
